services:
  django:
    container_name: backend-project
    build: .
    depends_on:
      - db
      - minio
      - redis
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: jason
      POSTGRES_PASSWORD: testpass
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: jason
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: minio-server
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    container_name: redis-server
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_data:
